In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/stock_percentage_difference.csv')

In [3]:
df.head(10)

,Unnamed: 0,level_0,transaction_date,ticker,asset_description,type,amount,representative,timestamp,merge_key,...,day_180_stock_perc_diff,sp_start,sp_30,sp_30_sp_perc_diff,sp_60,sp_60_sp_perc_diff,sp_90,sp_90_sp_perc_diff,sp_180,sp_180_sp_perc_diff
0,0,0,2020-03-18,CBRE,CBRE Group Inc Common Stock Class A,sale_partial,"$1,001 - $15,000",Susie Lee,1584504000,Susie Lee,...,0.321,2398.100098,2874.560059,0.199,2953.909912,0.232,3097.739990,0.292,3340.969971,0.393
1,1,1,2020-03-24,CNC,Centene Corporation,purchase,"$1,001 - $15,000",Susie Lee,1585022400,Susie Lee,...,0.254,2447.330078,2797.800049,0.143,2955.449951,0.208,3083.760010,0.260,3319.469971,0.356
2,2,2,2020-03-31,DG,Dollar General Corporation,purchase,"$1,001 - $15,000",Susie Lee,1585627200,Susie Lee,...,0.380,2584.590088,2912.429932,0.127,3055.729980,0.182,3130.010010,0.211,3298.459961,0.276
3,3,3,2020-02-21,ENV,"Envestnet, Inc",sale_partial,"$1,001 - $15,000",Susie Lee,1582261200,Susie Lee,...,0.016,3337.750000,2237.399902,-0.330,2799.310059,-0.161,2991.770020,-0.104,3389.780029,0.016
4,4,4,2020-03-17,LKQ,LKQ Corporation,sale_partial,"$1,001 - $15,000",Susie Lee,1584417600,Susie Lee,...,0.633,2529.189941,2799.550049,0.107,2863.699951,0.132,3115.340088,0.232,3340.969971,0.321
5,5,5,2020-02-05,NXST,"Nexstar Media Group, Inc. - Class A",sale_partial,"$1,001 - $15,000",Susie Lee,1580878800,Susie Lee,...,-0.299,3334.689941,2972.370117,-0.109,2663.679932,-0.201,2929.800049,-0.121,3271.120117,-0.019
6,6,6,2020-02-24,OKE,"ONEOK, Inc.",sale_partial,"$1,001 - $15,000",Susie Lee,1582520400,Susie Lee,...,-0.642,3225.889893,2447.330078,-0.241,2797.800049,-0.133,3036.129883,-0.059,3397.159912,0.053
7,7,7,2020-03-09,OKE,"ONEOK, Inc.",sale_full,"$1,001 - $15,000",Susie Lee,1583726400,Susie Lee,...,-0.298,2746.560059,2659.409912,-0.032,2881.189941,0.049,3190.139893,0.162,3426.959961,0.248
8,8,8,2020-03-16,QSR,Restaurant Brands International Inc. Common Sh...,sale_full,"$1,001 - $15,000",Susie Lee,1584331200,Susie Lee,...,0.533,2386.129883,2783.360107,0.166,2852.500000,0.195,3113.489990,0.305,3340.969971,0.400
9,9,9,2020-02-25,COO,"The Cooper Companies, Inc.",sale_full,"$1,001 - $15,000",Susie Lee,1582606800,Susie Lee,...,-0.104,3128.209961,2475.560059,-0.209,2836.739990,-0.093,3029.729980,-0.031,3397.159912,0.086

In [4]:
df.columns

Index(['Unnamed: 0', 'level_0', 'transaction_date', 'ticker',
       'asset_description', 'type', 'amount', 'representative', 'timestamp',
       'merge_key', 'people', 'state', 'party_x', 'total_senate_years',
       'total_house_years', 'total_years', 'donation_merge_key', 'name',
       'total_raised', 'total_from_small_donors', 'percent_from_small_donors*',
       'total_money_raised', 'party_y', 'start', 'day_30',
       'day_30_stock_perc_diff', 'day_60', 'day_60_stock_perc_diff', 'day_90',
       'day_90_stock_perc_diff', 'day_180', 'day_180_stock_perc_diff',
       'sp_start', 'sp_30', 'sp_30_sp_perc_diff', 'sp_60',
       'sp_60_sp_perc_diff', 'sp_90', 'sp_90_sp_perc_diff', 'sp_180',
       'sp_180_sp_perc_diff'],
      dtype='object')

In [5]:
df_final = pd.read_csv('data/final_dataset.csv')

In [6]:
df_final.columns

Index(['Unnamed: 0', 'level_0', 'transaction_date', 'ticker',
       'asset_description', 'type', 'amount', 'representative', 'timestamp',
       'merge_key', 'people', 'state', 'party_x', 'total_senate_years',
       'total_house_years', 'total_years', 'donation_merge_key', 'name',
       'total_raised', 'total_from_small_donors', 'percent_from_small_donors*',
       'total_money_raised', 'party_y', 'start', 'day_30', 'day_60', 'day_90',
       'day_180', 'sp_start', 'sp_30', 'sp_60', 'sp_90', 'sp_180'],
      dtype='object')

In [7]:
df_final[['start', 'day_30', 'day_60', 'day_90', 'sp_start', 'sp_30', 'sp_60', 'sp_90']]

,start,day_30,day_60,day_90,sp_start,sp_30,sp_60,sp_90
0,35.520000,44.500000,39.090000,46.740002,2398.100098,2874.560059,2953.909912,3097.739990
1,48.730000,69.239998,64.839996,63.360001,2447.330078,2797.800049,2955.449951,3083.760010
2,151.009995,175.300003,191.500000,189.479996,2584.590088,2912.429932,3055.729980,3130.010010
3,78.989998,48.860001,55.400002,70.970001,3337.750000,2237.399902,2799.310059,2991.770020
4,19.690001,19.840000,23.600000,25.980000,2529.189941,2799.550049,2863.699951,3115.340088
...,...,...,...,...,...,...,...,...
10076,48.080002,48.630001,47.599998,47.730000,1774.199951,1859.449951,1872.339966,1881.140015
10077,22.373737,24.553871,23.228115,21.755051,1792.500000,1854.290039,1857.619995,1883.680054
10078,54.450001,69.849998,60.389999,58.150002,1790.290039,1845.119995,1852.560059,1878.329956
10079,58.400002,63.660000,55.209999,50.759998,1790.290039,1845.119995,1852.560059,1878.329956
10080,23.990385,24.298077,24.634615,25.730770,1790.290039,1845.119995,1852.560059,1878.329956