In [165]:
import pandas as pd

In [166]:
house = pd.read_csv('data/house_stocks.csv')
senate = pd.read_csv('data/senate_stocks.csv')
donations = pd.read_csv('data/congress_donations.csv')

In [167]:
senate['transaction_date'] = pd.to_datetime(senate['transaction_date'])

In [168]:
senate.drop(columns = ['asset_type', 'comment', 'ptr_link'], inplace=True)

In [169]:
senate.head()

,transaction_date,owner,ticker,asset_description,type,amount,senator
0,2021-05-26,Spouse,--,"HSBC Contingent Autocall BMY <div class=""text-...",Sale (Full),"$15,001 - $50,000",Thomas R Carper
1,2021-05-26,Spouse,--,"HSBC Contingent Autocall BMY <div class=""text-...",Sale (Full),"$15,001 - $50,000",Thomas R Carper
2,2021-05-07,Spouse,--,"CS Contingent Autocall CSCO <div class=""text-m...",Purchase,"$15,001 - $50,000",Thomas R Carper
3,2021-05-01,Joint,--,"Bird Dog Hospitality Fund 1, LLC <div class=""t...",Purchase,"$15,001 - $50,000",Mike Rounds
4,2021-04-26,Spouse,WFC,Wells Fargo &amp; Company,Sale (Partial),"$1,001 - $15,000",Shelley M Capito

In [170]:
house['transaction_date'] = pd.to_datetime(house['transaction_date'])

In [171]:
house.drop(columns = ['disclosure_year', 'disclosure_date', 'district', 'ptr_link', 'cap_gains_over_200_usd'], inplace = True)

In [172]:
house.head()

,transaction_date,owner,ticker,asset_description,type,amount,representative
0,2020-02-24,joint,BHC,Bausch Health Companies Inc.,purchase,"$1,001 - $15,000",Hon. Susie Lee
1,2020-03-06,joint,BAH,Booz Allen Hamilton Holding Corporation,sale_full,"$1,001 - $15,000",Hon. Susie Lee
2,2020-03-23,joint,BYD,Boyd Gaming Corporation,sale_full,"$1,001 - $15,000",Hon. Susie Lee
3,2020-02-04,joint,CTLT,"Catalent, Inc.",purchase,"$1,001 - $15,000",Hon. Susie Lee
4,2020-03-18,joint,CBRE,CBRE Group Inc Common Stock Class A,sale_partial,"$1,001 - $15,000",Hon. Susie Lee

In [173]:
senate['representative'] = senate['senator']

In [174]:
senate.drop(columns = 'senator', inplace = True)

In [175]:
house['representative'] = [rep[5:] for rep in house['representative']]

In [176]:
donations['party'] = [name[-2] for name in donations['Name']]

In [177]:
donations.columns = donations.columns.str.lower().str.replace(' ','_')

In [178]:
donations['name'] = [name[:-4] for name in donations['name']]

In [179]:
def clean_name(name):
    first = name.split()[0]
    second = name.split()[1:]
    first_rev = first[::-1]
    for i, let in enumerate(first_rev):
        if let == let.upper():
            index = i
            break
    first = first[-(i+1):]
    second.insert(0,first)
    new = ' '.join(second)
    return new

In [180]:
donations['name'] = [clean_name(name) for name in donations['name']]

In [181]:
pd.merge(left = house, right = donations, how = 'inner', left_on = 'representative', right_on = 'name')

,transaction_date,owner,ticker,asset_description,type,amount,representative,name,total_raised,total_from_small_donors,percent_from_small_donors*,total_money_raised,party
0,2020-02-24,joint,BHC,Bausch Health Companies Inc.,purchase,"$1,001 - $15,000",Susie Lee,Susie Lee,$4748019,$284775,6.00%,Raised over $100k,D
1,2020-03-06,joint,BAH,Booz Allen Hamilton Holding Corporation,sale_full,"$1,001 - $15,000",Susie Lee,Susie Lee,$4748019,$284775,6.00%,Raised over $100k,D
2,2020-03-23,joint,BYD,Boyd Gaming Corporation,sale_full,"$1,001 - $15,000",Susie Lee,Susie Lee,$4748019,$284775,6.00%,Raised over $100k,D
3,2020-02-04,joint,CTLT,"Catalent, Inc.",purchase,"$1,001 - $15,000",Susie Lee,Susie Lee,$4748019,$284775,6.00%,Raised over $100k,D
4,2020-03-18,joint,CBRE,CBRE Group Inc Common Stock Class A,sale_partial,"$1,001 - $15,000",Susie Lee,Susie Lee,$4748019,$284775,6.00%,Raised over $100k,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4922,2021-04-22,self,--,"MDLIVE, INC",sale_full,"$50,001 - $100,000",Mario Diaz-Balart,Mario Diaz-Balart,$1590134,$2606,0.16%,Raised over $100k,R
4923,2020-07-14,--,TSLA,"Tesla, Inc.",sale_partial,"$15,001 - $50,000",Thomas Massie,Thomas Massie,$1457316,$426531,29.27%,Raised over $100k,R
4924,2020-03-18,dependent,DIS,Walt Disney Company,purchase,"$15,001 - $50,000",Justin Amash,Justin Amash,$1001120,$545077,54.45%,Raised over $100k,L
4925,2020-03-18,dependent,DIS,Walt Disney Company,purchase,"$1,001 - $15,000",Justin Amash,Justin Amash,$1001120,$545077,54.45%,Raised over $100k,L
4926,2020-03-18,dependent,DIS,Walt Disney Company,purchase,"$1,001 - $15,000",Justin Amash,Justin Amash,$1001120,$545077,54.45%,Raised over $100k,L

In [182]:
df = pd.concat([house, senate])
df.drop(columns = ['owner'], inplace = True)
df

,transaction_date,ticker,asset_description,type,amount,representative
0,2020-02-24,BHC,Bausch Health Companies Inc.,purchase,"$1,001 - $15,000",Susie Lee
1,2020-03-06,BAH,Booz Allen Hamilton Holding Corporation,sale_full,"$1,001 - $15,000",Susie Lee
2,2020-03-23,BYD,Boyd Gaming Corporation,sale_full,"$1,001 - $15,000",Susie Lee
3,2020-02-04,CTLT,"Catalent, Inc.",purchase,"$1,001 - $15,000",Susie Lee
4,2020-03-18,CBRE,CBRE Group Inc Common Stock Class A,sale_partial,"$1,001 - $15,000",Susie Lee
...,...,...,...,...,...,...
8551,2012-08-17,NaN,This filing was disclosed via scanned PDF. Use...,NaN,Unknown,Sheldon Whitehouse
8552,2012-08-16,NaN,This filing was disclosed via scanned PDF. Use...,NaN,Unknown,Pat Roberts
8553,2012-08-15,NaN,This filing was disclosed via scanned PDF. Use...,NaN,Unknown,Robert J Portman
8554,2012-08-02,NaN,This filing was disclosed via scanned PDF. Use...,NaN,Unknown,Thomas R Carper
8555,2012-07-25,NaN,This filing was disclosed via scanned PDF. Use...,NaN,Unknown,Benjamin L Cardin

In [183]:
donations.shape

(537, 6)

In [184]:
df.dropna(inplace=True)
df

,transaction_date,ticker,asset_description,type,amount,representative
0,2020-02-24,BHC,Bausch Health Companies Inc.,purchase,"$1,001 - $15,000",Susie Lee
1,2020-03-06,BAH,Booz Allen Hamilton Holding Corporation,sale_full,"$1,001 - $15,000",Susie Lee
2,2020-03-23,BYD,Boyd Gaming Corporation,sale_full,"$1,001 - $15,000",Susie Lee
3,2020-02-04,CTLT,"Catalent, Inc.",purchase,"$1,001 - $15,000",Susie Lee
4,2020-03-18,CBRE,CBRE Group Inc Common Stock Class A,sale_partial,"$1,001 - $15,000",Susie Lee
...,...,...,...,...,...,...
8321,2014-01-24,FB,"Facebook, Inc. (NASDAQ)",Purchase,"$1,001 - $15,000",Susan M Collins
8322,2014-01-24,CRM,"Salesforce.com, Inc (NYSE)",Purchase,"$1,001 - $15,000",Susan M Collins
8323,2014-01-24,GE,General Electric Company (NYSE),Sale (Partial),"$1,001 - $15,000",Susan M Collins
8327,2014-01-21,--,CVS Caremark Corporation,Purchase,"$1,001 - $15,000",John F Reed
8328,2014-01-21,--,CVS Caremark Corporation,Purchase,"$1,001 - $15,000",John F Reed

In [185]:
set([name for name in df['representative'] if name not in donations])

{'A. Mitchell Mcconnell, Jr.',
 'Abigail Spanberger',
 'Adam B. Schiff',
 'Adam Kinzinger',
 'Alan S. Lowenthal',
 'Andrew Garbarino',
 'Angus S King, Jr.',
 'Ann Wagner',
 'Anthony E. Gonzalez',
 'Ashley Hinson Arenholz',
 'Austin Scott',
 'Benjamin L Cardin',
 'Bill Flores',
 'Bill Huizenga',
 'Bill Pascrell',
 'Billy Long',
 'Bob Gibbs',
 'Bradley S. Schneider',
 'Brian Mast',
 'Carol Devine Miller',
 'Carolyn B. Maloney',
 'Charles J. "Chuck" Fleischmann',
 'Chellie Pingree',
 'Cheri Bustos',
 'Chris Van Hollen',
 'Christopher A Coons',
 'Christopher L. Jacobs',
 'Cory A Booker',
 'Daniel Crenshaw',
 'Daniel Meuser',
 'Daniel S Sullivan',
 'David A Perdue , Jr',
 'David B. McKinley',
 'David Cheston Rouzer',
 'David E. Price',
 'David Kustoff',
 'David P. Joyce',
 'David P. Roe',
 'David Trone',
 'Dean Phillips',
 'Debbie Dingell',
 'Debbie Wasserman Schultz',
 'Deborah K. Ross',
 'Donald Sternoff Beyer',
 'Donald Sternoff Honorable Beyer',
 'Donna Shalala',
 'Doris O. Matsui',
 'Doug Lamborn',
 'Dwight Evans',
 'Earl Blumenauer',
 'Earl Leroy Carter',
 'Ed Case',
 'Ed Perlmutter',
 'Elaine Luria',
 'Eleanor Holmes Norton',
 'Francis Rooney',
 'Frank Pallone',
 'Fred Upton',
 'Garret Graves',
 'Gary C Peters',
 'George Holding',
 'Gerald E. Connolly',
 'Gilbert Cisneros',
 'Grace Meng',
 'Greg Gianforte',
 'Greg Steube',
 'Gus M. Bilirakis',
 'Hakeem S. Jeffries',
 'Harley E. Rouda',
 'Harold Dallas Rogers',
 'J John (Tj) Cox',
 'Jacklyn S Rosen',
 'James Comer',
 'James E Hon Banks',
 'James E. Banks',
 'James French Hill',
 'James Hagedorn',
 'James M Inhofe',
 'James R. Langevin',
 'Jeanne Shaheen',
 'Jerry Moran,',
 'Joe Courtney',
 'John A Barrasso',
 'John A. Yarmuth',
 'John B. Larson',
 'John Boozman',
 'John Cornyn',
 'John Curtis',
 'John F Reed',
 'John Hoeven',
 'John N Kennedy',
 'John Rutherford',
 'John W Hickenlooper',
 'Joseph D. Morelle',
 'Joseph Manchin, Iii',
 'Joseph P. Kennedy',
 'Josh Gottheimer',
 'Judy Chu',
 'Justin Amash',
 'K. Michael Conaway',
 'Katherine M. Clark',
 'Kathy Castor',
 'Kathy Manning',
 'Kelly Loeffler',
 'Kenny Marchant',
 'Kevin Hern',
 'Kim Schrier',
 'Kurt Schrader',
 'Ladda Tammy Duckworth',
 'Lamar Alexander',
 'Linda T. Sanchez',
 'Lloyd Doggett',
 'Lloyd K. Smucker',
 'Lois Frankel',
 'Maria Cantwell',
 'Marie Newman',
 'Mario Diaz-Balart',
 'Marjorie Taylor Greene',
 'Mark Dr Green',
 'Mark Green',
 'Mark R Warner',
 'Matt Gaetz',
 'Michael  B Enzi',
 'Michael D Crapo',
 'Michael F Bennet',
 'Michael Garcia',
 'Michael John Gallagher',
 'Michael K. Simpson',
 'Michael Patrick Guest',
 'Michael T. McCaul',
 'Michael Waltz',
 'Mike Kelly',
 'Mike Rounds',
 'Mikie Sherrill',
 'Mo Brooks',
 'Nancy Pelosi',
 'Neal Patrick Dunn MD, FACS',
 'Neal Patrick MD, FACS Dunn',
 'Neal Patrick MD, Facs Dunn',
 'Nicholas Van Taylor',
 'Pat Roberts',
 'Patrick J Toomey',
 'Patrick T. McHenry',
 'Patty Murray',
 'Pete Sessions',
 'Peter J. Visclosky',
 'Peter Welch',
 'Rafael E Cruz',
 'Richard W. Allen',
 'Rick Scott',
 'Robert C. "Bobby" Scott',
 'Robert E. Latta',
 'Robert J Portman',
 'Robert J. Wittman',
 'Robert P Casey, Jr.',
 'Roger F Wicker',
 'Roger W. Marshall',
 'Rohit Khanna',
 'Ron Johnson',
 'Ron L Wyden',
 'Ron Wyden',
 'Roy Blunt',
 'S. Raja Krishnamoorthi',
 'Sara Jacobs',
 'Scott Franklin',
 'Scott H. Peters',
 'Sean Patrick Maloney',
 'Seth Moulton',
 'Sheldon Whitehouse',
 'Shelley M Capito',
 'Steve Cohen',
 'Steve Daines',
 'Susan A. Davis',
 'Susan M Collins',
 'Susan W. Brooks',
 'Susie Lee',
 'Suzan K. DelBene',
 'Tammy Duckworth',
 'Thomas Massie',
 'Thomas R Carper',
 'Thomas R Tillis',
 'Thomas Udall',
 'Tim Burchett',
 'Timothy M Kaine',
 'Tina Smith',
 'Tom Malinowski',
 "Tom O'Halleran",
 'Tom Rice',
 'Trey Hollingsworth',
 'Vern Buchanan',
 'Victoria Spartz',
 'Virginia Foxx',
 'W. Greg Steube',
 'William Cassidy',
 'William F Hagerty, Iv',
 'William R. Keating',
 'William R. Timmons',
 'Wm. Lacy Clay',
 'Zoe Lofgren',
 'cott Franklin',
 'eter Meijer'}

In [186]:
dfmerge = pd.merge(left = df, right = donations, how = 'inner', left_on = 'representative', right_on = 'name')

In [188]:
df.to_csv('data/senate_and_house.csv')